---
- name: "2023 - Day 1"
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:
    - name: "open file"
      delegate_to: localhost
      set_fact:
        test: "{{ lookup('file', '{{ playbook_dir }}/input.txt') }}"

    # - name: "loop over file "
